server:
  port: 2243
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher



  
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret-key: 3EDB8C08B982F6A8957C02846A8F04B0C995880D7C5C5906F858578496A45C4A7516FBB25C7C2B46D1CF448C422536B2B1523ACFB83BC9C5A32EAEA987511BAF



---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: local
