spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://refuel-aromanote-dev.c4bcyevfqzrs.ap-northeast-2.rds.amazonaws.com:3306/aromanote_dev
    username: jayjang
    password: devgkgksmf1!
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  level:
    root: info
    com.rf.aromanote: debug
    org.hibernate.type: trace
    org.hibernate.sql: debug



